OCL definition and documentation
openservicescloud/xpanse pull request #13
Opened 2023-01-12 06:38 UTC by WangLiNaruto

2023-01-29 01:54 UTC, iskey requested changes

2023-01-29 01:54 UTC, iskey commented on modules/ocl-loader/src/main/resources/resources.yaml
> +  - category: vpc
```suggestion
  - category: kind
```
How about replacing the `category` with `kind`?

2023-01-29 01:54 UTC, iskey commented on modules/ocl-loader/src/main/resources/resources.yaml
> +    properties:
How do you think you could use existing `securities`?

2023-01-29 01:54 UTC, iskey commented on modules/ocl-loader/src/main/resources/resources.yaml
> +  - category: baseImage
```suggestion
  - category: image
```
The image is ok.

2023-01-29 01:54 UTC, iskey commented on modules/ocl-loader/src/main/resources/resources.yaml
> +  - category: provisioner
I think we no longer need this kind now.

2023-01-29 01:54 UTC, iskey commented on modules/ocl-loader/src/main/resources/resources.yaml
> +    properties:
Please consider how to reuse existing images.

2023-01-29 01:54 UTC, iskey commented on modules/ocl-loader/src/main/resources/resources.yaml
> +    properties:
Please consider how to reuse the existing subnet.

2023-01-29 01:54 UTC, iskey commented on modules/ocl-loader/src/main/resources/resources.yaml
> +    properties:
Please consider how to reuse the existing VPC.

2023-01-31 01:40 UTC, baixinsui commented on modules/ocl-loader/src/main/resources/resources.yaml
> +    properties:
Can we add key "id" in the properties  and fill the value with the instance  id of existed resource then judge whether the value of id is empty. If the id value is not empty, use the existing resource. Otherwise, create a new resource?

2023-01-31 01:41 UTC, baixinsui commented on modules/ocl-loader/src/main/resources/resources.yaml
> +  - category: provisioner
remove the resource of packer?

2023-02-16 08:59 UTC, iskey approved these changes

2023-02-16 08:59 UTC, iskey commented
looks good.

2023-02-16 08:59 UTC, merged